apiVersion: v2
appVersion: 1.12.1
description: A chart to deploy code servers for your Dagster deployment.
icon: https://dagster.io/images/brand/logos/dagster-primary-mark.png
keywords:
- analytics
- data-orchestrator
- data-pipelines
- etl
- workflow
kubeVersion: '>= 1.18.0-0'
maintainers:
- email: support@dagsterlabs.com
  name: Dagster Labs
  url: https://dagster.io/about
name: dagster-user-deployments
sources:
- https://github.com/dagster-io/dagster/tree/master/helm/dagster/charts/dagster-user-deployments
type: application
version: 1.12.1
