---
secretsprovider: awskms://alias/infrastructure-secrets-qa
encryptedkey: AQICAHijXuVxVlAL6bY9xCOrzO3YYhFlQBPt6jNyJGkhYu+q4QHhXlvPfNhuE+oHmMQQseu9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPLfTZMrnTgwBA2kfAgEQgDupw9ff+ck3TY6C9Z9MJ3nBjVRZGqljmBh4OmWLRPsR6iBm59Z1RTIcgaxHjChEkMM0Y9+GGF6j3nM6Qw==
config:
  aws:region: us-east-1
  ocw_site:domains:
    draft:
    - draft-qa.ocw.mit.edu
    live:
    - live-qa.ocw.mit.edu
    - ocwnext-rc.odl.mit.edu
    test:
    - test-qa.ocw.mit.edu
