# ALTERNATE_WORKER_QUEUES: lms  # Already has a sane default in the code
COURSE_AUTHORING_MICROFRONTEND_URL: /authoring
DISCUSSIONS_INCONTEXT_LEARNMORE_URL: https://openedx.atlassian.net/wiki/spaces/COMM/pages/3470655498/Discussions+upgrade+Sidebar+and+new+topic+structure
GIT_REPO_EXPORT_DIR: /openedx/data/export_course_repos
ENABLE_CONTENT_LIBRARIES: true # ADDED
ENABLE_INSTRUCTOR_LEGACY_DASHBOARD: true # ADDED
ENABLE_RAPID_RESPONSE_AUTHOR_VIEW: true # ADDED
FEATURES:
  ENABLE_INSTRUCTOR_BACKGROUND_TASKS: true # ADDED
  ENABLE_NEW_BULK_EMAIL_EXPERIENCE: true # ADDED
  MAX_PROBLEM_RESPONSES_COUNT: 10000 # ADDED
  PREVIEW_LMS_BASE: preview-ci.mitx.mit.edu # ADDED
GIT_EXPORT_DEFAULT_IDENT:
  name: MITx Online
  email: mitx-devops@mit.edu

PARSE_KEYS: {}
#################################################################################################
# Disable `Learn More ...` links that redirect to edx.readthedocs.io in the Authoring MFE cards #
#################################################################################################
CALCULATOR_HELP_URL: ''
DISCUSSIONS_HELP_URL: ''
EDXNOTES_HELP_URL: ''
PROGRESS_HELP_URL: ''
SEGMENT_IO: false # ADDED
TEAMS_HELP_URL: ''
TEXTBOOKS_HELP_URL: ''
WIKI_HELP_URL: ''
CUSTOM_PAGES_HELP_URL: ''
COURSE_LIVE_HELP_URL: ''
ORA_SETTINGS_HELP_URL: 'https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/course_assets/pages.html#configuring-course-level-open-response-assessment-settings'
