---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHi3MZ/Pjy2dahB1Qm+zKkKDPV1b9MYPGp7k649HPjmOHAGQnkx6GhWKU0ZJEvmaG6UGAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTWzBS8XWzvVovcnfAgEQgDsyuo1Jz9MHpTv3m2sOW31aDErF1KT00+YyBWpy40WyecGE30OCUjMkxDXaKgxqDy5tMVRIj0qu0WYX8Q==
config:
  aws:region: us-east-1
  codejail:auto_scale:
    desired: 1
    max: 3
    min: 1
  codejail:business_unit: mitxonline
  codejail:target_vpc: mitxonline_vpc
  codejail:deploy_to_k8s: true
  codejail:deploy_to_ec2: false
  codejail:replicas: 1
  consul:address: https://consul-mitxonline-ci.odl.mit.edu
  codejail:target_cluster: applications
