---
secretsprovider: awskms://alias/infrastructure-secrets-qa
encryptedkey: AQICAHi7xhTkB8tf1ObyPMxDhODJja4Mn4jyIo32zZVlOiZPFgGO2YRBlHwYnGmjMJ32HLyhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSX3+DbXTwJ2uVLMCAgEQgDs40O5XfEHBMS2dyZG/U+fsZHw4rvmm4CQDEH2vjQku2rFMzecG5IhnKe0lDMIObU30dklmmzWnebsFzA==
config:
  aws:region: us-east-1
  codejail:business_unit: mitxpro
  codejail:replicas: 2
  codejail:target_cluster: applications
