---
secretsprovider: awskms://alias/infrastructure-secrets-qa
encryptedkey: AQICAHi7xhTkB8tf1ObyPMxDhODJja4Mn4jyIo32zZVlOiZPFgFqyheTEwQhQwt19Cm5Z2wyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUHRADb5VO/Osd+QMAgEQgDthoUItjofWZZROiCvTVCFgPdVM1f3tWDvxoezDTWseixH0X/RXXDnIDnOXDiC9dHp/ZRoXORovMifXGg==
config:
  aws:region: us-east-1
  codejail:auto_scale:
    desired: 1
    max: 3
    min: 1
  codejail:business_unit: residential-staging
  codejail:target_vpc: residential_mitx_staging_vpc
  consul:address: https://consul-mitx-qa.odl.mit.edu
  codejail:deploy_to_k8s: true
  codejail:replicas: 2
  codejail:target_cluster: residential
