---
secretsprovider: awskms://alias/infrastructure-secrets-qa
encryptedkey: AQICAHi7xhTkB8tf1ObyPMxDhODJja4Mn4jyIo32zZVlOiZPFgFWC20dUtAsq29JCqVMsqAzAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVQnoSwWd1iDkYVrzAgEQgDv+yzxf6VlCobqGY6jWf6a8z2HerL2fjWsImqz/TgW/Ec09+VtTdUYhOssqHCokFL2AanGlb1n4n/3QoQ==
config:
  aws:region: us-east-1
  codejail:business_unit: residential
  codejail:replicas: 2
  codejail:target_cluster: residential
