---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHg/+QzF9hGIaoayDitgnEVHEhuaANONVQQOnqpkIsol1gFIp45VyYwQaGk+qWWxFdcAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMCiMPJ86XDVgWbNCXAgEQgDv9PVQtOO4pqjOvJTGrqe9X598O4IAjEl4Ldk7DMmDNo+F6z3nAGyLNMkqwRNMB6sXJ8tDvTZ6ZKpyEmw==
config:
  aws:region: us-east-1
  codejail:business_unit: mitxpro
  codejail:replicas: 4
  codejail:target_cluster: applications
