---
secretsprovider: awskms://alias/infrastructure-secrets-qa
encryptedkey: AQICAHi7xhTkB8tf1ObyPMxDhODJja4Mn4jyIo32zZVlOiZPFgFH5vIucphRR7Mq6OdG1kZeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHWKReg8qb4MysUw8AgEQgDuT6iLKN7HMLYRcVHEZL8Igienqic9lhMV77liJVysyDmU1cEyHwZ54z8Q2N5YGhqPNkmQvKcDKRdj+5g==
config:
  aws:region: us-east-1
  codejail:replicas: 2
  codejail:business_unit: mitxonline
  codejail:target_cluster: applications
