---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHi3MZ/Pjy2dahB1Qm+zKkKDPV1b9MYPGp7k649HPjmOHAGQnkx6GhWKU0ZJEvmaG6UGAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTWzBS8XWzvVovcnfAgEQgDsyuo1Jz9MHpTv3m2sOW31aDErF1KT00+YyBWpy40WyecGE30OCUjMkxDXaKgxqDy5tMVRIj0qu0WYX8Q==
config:
  aws:region: us-east-1
  codejail:business_unit: mitxonline
  codejail:replicas: 1
  codejail:target_cluster: applications
