---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHg/+QzF9hGIaoayDitgnEVHEhuaANONVQQOnqpkIsol1gFmLVxyy2hwwSaJxQxImVj4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMByjuTZCa/787HRlTAgEQgDvzT7yifAD521iKxKHtlL1JvmzWyS7l8WAZNiqS+vdFt61fQmcthwGmSlwnMBTgwAI3rxNbaQiUcztEQg==
config:
  aws:region: us-east-1
  codejail:business_unit: residential
  codejail:replicas: 5
  codejail:target_cluster: residential
