---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHi+npazf3LfzV9oCtcYyCMYLOzaQhbo9xt6lJVVpz9tkQEuBF2geTAk/sSHq4exrj7bAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3eR6c0gzKKLorTWjAgEQgDtmbnQSLPTgsgvN0ceDxQfu3YFVeuIf4W00zyE1INRuM4tkNSKamvZFtt/33YP/IdJiUXd8BeF4DzKTaA==
config:
  aws:region: us-east-1
  codejail:business_unit: mitxpro
  codejail:replicas: 1
  codejail:target_cluster: applications
