---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHg/+QzF9hGIaoayDitgnEVHEhuaANONVQQOnqpkIsol1gFMzAtzjNTziE5CH3/1nVc/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4ACvZ1m2/GKeVvfTAgEQgDvOJk9uXXGMludwr62Y4tZe/Qo28GGqbhGdTHiEgbWVXEdexmgDoqd7Tr+xeYJebx2kAieSFC6o/1GSnA==
config:
  aws:region: us-east-1
  codejail:replicas: 5
  codejail:business_unit: mitxonline
  codejail:target_cluster: applications
