---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHhMkpkBpCvmFjhyfy75ENALRrbg42uOs9cUsFNLXqPnagE98/AcVuZYFrvssgrUMKxnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMQL4gwDdQmhst3Db1AgEQgDvJjcAUXmbNIex0rkn7tft19foLBWZYBR6I6PjApIn0WgqpeS366GjOvBvIl4EJHHyM40Pr3OLfWcO6Zw==
config:
  aws:region: us-east-1
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
  starrocks:root_password:
    secure: v1:w7XB0bIL9sTAauXL:Iq4pX5ZCeISL7XkB+aTI5YsyncAt3C4ZVJVbjJHCuTZhhTviyOI7oE9HEu+oVGGTFHh7snFElkqQflrGPCeUfcb8uHaJ5j+z3DLYbGNfCNE=
