---
secretsprovider: awskms://alias/infrastructure-secrets-qa
encryptedkey: AQICAHjZAY5LtmRWGljev0oiDGn0jR5cRwD4IVXCn50TW5i0qQE2MbaMHwWMskzdnFWfe+hsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMmpzhOokScVcdXhTYAgEQgDvk9g7JDDlwSixjXqkRqrZ8yAPaarOUw+Y6yHmjFiT/4hi8SSh2nEWa19MEqMTP4PaZWlgmpT9tS5avnA==
config:
  jupyterhub:deployments:
  - name: jupyterhub
    domain: nb.rc.learn.mit.edu
    namespace: jupyter
    db_name: jupyterhub
    apisix_ingress_class: apache-apisix
    admin_users:
    - "admin"
    menu_override_file: menu_override.json
    disabled_extension_file: disabled_extensions.json
    extra_config_file: dynamicImageConfig.py
    vault_policy_file: jupyterhub_policy.hcl
    proxy_port: 30000
  - name: jupyterhub-authoring
    domain: authoring.nb.rc.learn.mit.edu
    namespace: jupyter-authoring
    db_name: jupyterhub_authoring
    apisix_ingress_class: apache-apisix
    authenticator_class: shared-password
    admin_users:
    - "admin"
    menu_override_file: author_menu_override.json
    disabled_extension_file: author_disabled_extensions.json
    extra_config_file: dynamicImageConfig.py
    vault_policy_file: jupyterhub_policy.hcl
    proxy_port: 30001
    user_placeholder_replicas: 1
    notebook_bucket: jupyter-courses-qa
    shared_password:
      secure: v1:6jn5qRWKDbtbGB9M:VA+J7wwlJM6aw+nrn6gSU3+ndpxXRYDIWwi7x9NuNMxY8CfCesxQuoczRu04L0PhPC8f5qbDnWkF/PB9huub1feGkETJkr8EAr0b3CpGeDo=
  jupyterhub:target_vpc: "applications_vpc"
  jupyterhub:business_unit: "mit-learn"
  aws:region: us-east-1
  vault:address: https://vault-qa.odl.mit.edu
  vault_server:env_namespace: operations.qa
  jupyterhub:rds_password:
    secure: v1:azvoUOJDNjEzqmDX:CVO6sIlnFR6uTjq/5mK2kHhIh7DAAR3D6FXX4HkcTAdhyZwBhAhU9c4RikJvIhyPLUqJDZELr7dZzp0=
