---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHi3MZ/Pjy2dahB1Qm+zKkKDPV1b9MYPGp7k649HPjmOHAFqnCOCAZSgyF1ZWf0UadNJAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMo8Vlyuwrp1ocOIPzAgEQgDtuHDo3PpUPnI8Ld39Bq5dR9m0mnxpqjeqfAWopoZssGhgjoG9CfYrqTNsw4qr8fHcnvtAHzJoKzyDD4w==
config:
  jupyterhub:deployments:
  - name: jupyterhub
    domain: nb.ci.learn.mit.edu
    namespace: jupyter
    db_name: jupyterhub
    apisix_ingress_class: apache-apisix
    admin_users:
    - "admin"
    menu_override_file: menu_override.json
    disabled_extension_file: disabled_extensions.json
    extra_config_file: dynamicImageConfig.py
    proxy_port: 30000
  - name: jupyterhub-authoring
    domain: authoring.nb.ci.learn.mit.edu
    namespace: jupyter-authoring
    db_name: jupyterhub_authoring
    apisix_ingress_class: apache-apisix
    admin_users:
    - "admin"
    menu_override_file: author_menu_override.json
    disabled_extension_file: author_disabled_extensions.json
    extra_config_file: dynamicImageConfig.py
    proxy_port: 30001
  jupyterhub:target_vpc: "applications_vpc"
  jupyterhub:business_unit: "mit-learn"
  aws:region: us-east-1
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
  jupyterhub:shared_password:
    secure: v1:sKBL3tBJ/EGDkmrt:5sJUBSl6ehXuwdMvMpwILzdsvHkycmXCUt43ru1SsO9sePH9WQNlVy6giJ1Y2wXiYu9dQx9NfGYb+Nnk4t7T90Gjz5Ouc2NKGT05rKuDMjk=
  jupyterhub:rds_password:
    secure: v1:ae+uadhbZC0VnnI5:p0QKNNy8xscV8K69VTTcLIca6BfvEoarQ4ZsRsa2pGAGoU3IDDe48fJVCYvVLwDvufpvbLUnR88MJP4=
