---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHi3FG4qowC3UzOLWOAA4Y9/RTwqKjovG3wyVVYDxkR+zAFdGH4t37aqxE9PJ8UPkhA5AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMI06fTZM6kIRX1HtCAgEQgDsJeFqCvt1KmnCTldvOLaoIm71PZvYvfUb2Prnju0nFBXaHid8dJxvTcslib6igE/ljh/HoNat1KTj4Vg==
config:
  digital-credentials:issuer_coordinator_domain: dcc.learn.mit.edu
  vault:address: https://vault-production.odl.mit.edu
  vault_server:env_namespace: operations.production
