---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHhMkpkBpCvmFjhyfy75ENALRrbg42uOs9cUsFNLXqPnagGpMAiA0lehNbRmmMZUfh+wAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMEsi8U+fCgbxSVb9jAgEQgDsOjStqZU02uF5W1J/DS2GFauSSJJ3PjbIe0I6fjyz399xfSJPYl1KDULIYDdXWfiMJo4j/54QWdEboDg==
config:
  digital-credentials:issuer_coordinator_domain: dcc.ci.learn.mit.edu
