---
secretsprovider: awskms://alias/infrastructure-secrets-qa
encryptedkey: AQICAHjZAY5LtmRWGljev0oiDGn0jR5cRwD4IVXCn50TW5i0qQHzk3ZqJWakrU/mDNmKkJH9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/11yDfkssWK12Li5AgEQgDseXkTo+NuGojGGq9+/P8eWHkh98HKAc960yXJvvn5uT2QeFUJ8LaVbp1aZUQ1ygdaThDkdZADFpHUSyQ==
config:
  digital-credentials:issuer_coordinator_domain: dcc.rc.learn.mit.edu
