---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHg/+QzF9hGIaoayDitgnEVHEhuaANONVQQOnqpkIsol1gH/8B9HwincPwBG2gtLZZyLAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMTU3dSX79VQQGTRu4AgEQgDsM0riTMyEuRQX2E/Q+TMBn3AdSvo8gR5aGeebKq0gTjYHI2vfwjuVETzxFOhXMUwsh8gZ9wzGMX2vdKw==
config:
  aws:region: us-east-1
  consul:address: https://consul-xpro-production.odl.mit.edu
  forum:auto_scale:
    desired: 3
    max: 10
    min: 3
  forum:business_unit: mitxpro
  forum:instance_type: t3a.medium
  forum:target_vpc: xpro_vpc
  forum:openedx_version_tag: maple.master
  vault:address: https://vault-production.odl.mit.edu
  vault_server:env_namespace: operations.production
