---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHg/+QzF9hGIaoayDitgnEVHEhuaANONVQQOnqpkIsol1gHaXdOgJQNVZipYBEMrjnq2AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMveJ6nv2z4uQIWZBVAgEQgDuZfkB3otCyaR5Z5Lz1KbFObdVmXafnFEJ2Fn91n/bGIDMrIk6INxAS5tg05t30zyu5YfnroXzP1Ib3Uw==
config:
  aws:region: us-east-1
  consul:address: https://consul-mitx-production.odl.mit.edu
  forum:auto_scale:
    desired: 3
    max: 10
    min: 3
  forum:business_unit: residential
  forum:instance_type: t3a.medium
  forum:target_vpc: residential_mitx_vpc
  vault:address: https://vault-production.odl.mit.edu
  vault_server:env_namespace: operations.production
