---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHjs8ajWpT7YRhWXwI//wPkHX53RHlo0DjkgQOwCBTUBwQEYYDBvwjE0WZgwkWnOd4wFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMDjSX7HsLpPYqa+1jAgEQgDuMf0vGHUOPUUXXlCICCyakQUq4hey4vGpMgRvsMNiE6EYfFLqz/ADxPIR/BlwXdHXP8MOfoap3i3bKaw==
config:
  aws:region: us-east-1
  consul:address: https://consul-mitx-ci.odl.mit.edu
  forum:auto_scale:
    desired: 1
    max: 2
    min: 1
  forum:business_unit: residential
  forum:target_vpc: residential_mitx_vpc
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
