---
secretsprovider: awskms://alias/infrastructure-secrets-qa
encryptedkey: AQICAHi7xhTkB8tf1ObyPMxDhODJja4Mn4jyIo32zZVlOiZPFgFqyheTEwQhQwt19Cm5Z2wyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUHRADb5VO/Osd+QMAgEQgDthoUItjofWZZROiCvTVCFgPdVM1f3tWDvxoezDTWseixH0X/RXXDnIDnOXDiC9dHp/ZRoXORovMifXGg==
config:
  aws:region: us-east-1
  consul:address: https://consul-mitx-qa.odl.mit.edu
  forum:auto_scale:
    desired: 1
    max: 2
    min: 1
  forum:business_unit: operations
  forum:target_vpc: residential_mitx_vpc
  vault:address: https://vault-qa.odl.mit.edu
  vault_server:env_namespace: operations.qa
