---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHg/+QzF9hGIaoayDitgnEVHEhuaANONVQQOnqpkIsol1gGBr+9wC0RNsmO2noJTdlAKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM21BXoZIb5hh7mVp5AgEQgDv1ca9zhVykIhELlmD6D+gUVkevz/1iWsxJnkJOJxVAUhviUhLwLKkV8qu3xPBrZ8sTSWB88CFHkxQZcw==
config:
  aws:region: us-east-1
  consul:address: https://consul-mitxonline-production.odl.mit.edu
  forum:auto_scale:
    desired: 3
    max: 10
    min: 3
  forum:business_unit: mitxonline
  forum:instance_type: t3a.medium
  forum:openedx_version_tag: master
  forum:target_vpc: mitxonline_vpc
  vault:address: https://vault-production.odl.mit.edu
  vault_server:env_namespace: operations.production
