---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHjs8ajWpT7YRhWXwI//wPkHX53RHlo0DjkgQOwCBTUBwQFdtdIjrHnLIoWB/UbBuGhnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZhxvEbwZGsYEUJc9AgEQgDtJ2M237n4bkl9H5Uukso2pOKhAPbv2EwI/p/k4Ru5AUEXPgkqP+K43hBH1jmASwuVhne5vuzGvMd/lLw==
config:
  aws:region: us-east-1
  consul:address: https://consul-mitx-staging-ci.odl.mit.edu
  forum:auto_scale:
    desired: 1
    max: 2
    min: 1
  forum:business_unit: residential-staging
  forum:target_vpc: residential_mitx_staging_vpc
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
