---
secretsprovider: awskms://alias/PulumiSecrets
encryptedkey: AQICAHionUR8LBW1ALuVC0rCH3AE2oQIfGMCx3XmpDH9HjM2LQHCl1F5CkB9y+4pa4cdh1HBAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcZ6bDFT2B+PzwjJ7AgEQgDs424r99BfDPCOwQgTVPkU4mnyTYutKvNNZD+B6unrbHuCLMwAtZPfho2l/me8vNJXmrPe0/oHQRUQQFQ==
config:
  aws:region: us-east-1
  heroku:app_id:
    secure: v1:duXmfmfPUoM4SwNT:8rP1PxDYqJyDwTcMqMvIjCvmj2Juv6kXFRE0cFqdTNjM20pveCAEVvINeGNlFlUCGqhXKA==
  heroku_app:vars:
    ACCESS_TOKEN_URL: "https://sso-ci.ol.mit.edu/realms/olapps/protocol/openid-connect/token"
    AUTHORIZATION_URL: "https://sso-ci.ol.mit.edu/realms/olapps/protocol/openid-connect/auth"
    AWS_STORAGE_BUCKET_NAME: 'odl-discussions-ci'
    CELERY_WORKER_MAX_MEMORY_PER_CHILD: "125000"
    CLOUDFRONT_DIST: "d28ic9ywb63ioi"
    CORS_ALLOWED_ORIGINS: '["https://micromasters-ci.odl.mit.edu", "https://ocwnext-rc.odl.mit.edu",
      "https://draft-qa.ocw.mit.edu", "https://live-qa.ocw.mit.edu"]'
    DEBUG: "False"
    EDX_LEARNING_COURSE_BUCKET_NAME: ""
    ENABLE_INFINITE_CORRIDOR: "True"
    FEATURE_COURSE_UI: "True"
    FEATURE_KEYCLOAK_ENABLED: "True"
    GA_G_TRACKING_ID: "G-N6Y7B0Z3JL"
    GA_TRACKING_ID: "UA-5145472-29"
    INDEXING_API_USERNAME: "od_mm_ci_api"
    KEYCLOAK_BASE_URL: "https://sso-ci.ol.mit.edu"
    KEYCLOAK_REALM_NAME: "olapps"
    MAILGUN_FROM_EMAIL: 'MIT Open <no-reply@discussions-mail.odl.mit.edu'
    MAILGUN_SENDER_DOMAIN: "discussions-mail.odl.mit.edu"
    MAILGUN_URL: "https://api.mailgun.net/v3/discussions-mail.odl.mit.edu"
    MICROMASTERS_BASE_URL: "https://micromasters-ci.odl.mit.edu"
    MICROMASTERS_CATALOG_API_URL: "https://micromasters-ci.odl.mit.edu/api/v0/catalog/"
    MICROMASTERS_COURSE_URL: "https://micromasters-ci.odl.mit.edu/api/v0/courseruns/"
    MICROMASTERS_EXTERNAL_LOGIN_URL: "https://micromasters-ci.odl.mit.edu/discussions"
    NEW_RELIC_APP_NAME: "discussions-ci"
    OCW_ITERATOR_CHUNK_SIZE: "300"
    OCW_LEARNING_COURSE_BUCKET_NAME: "open-learning-course-data-ci"
    OCW_NEXT_AWS_STORAGE_BUCKET_NAME: "ol-ocw-studio-app-qa"
    OCW_NEXT_BASE_URL: "https://live-qa.ocw.mit.edu/"
    OCW_NEXT_LIVE_BUCKET: "ocw-content-live-qa"
    OCW_UPLOAD_IMAGE_ONLY: "True"
    OIDC_ENDPOINT: "https://sso-ci.ol.mit.edu/realms/olapps"
    OPEN_DISCUSSIONS_BASE_URL: "https://discussions-ci.odl.mit.edu"
    OPEN_DISCUSSIONS_COOKIE_DOMAIN: "odl.mit.edu"
    OPEN_DISCUSSIONS_COOKIE_NAME: "discussionsci"
    OPEN_DISCUSSIONS_CORS_ORIGIN_WHITELIST: '["https://micromasters-ci.odl.mit.edu",
      "https://ocwnext-rc.odl.mit.edu", "https://draft-qa.ocw.mit.edu", "https://live-qa.ocw.mit.edu"]'
    OPEN_DISCUSSIONS_ENVIRONMENT: "ci"
    OPEN_DISCUSSIONS_LOG_LEVEL: "INFO"
    OPEN_DISCUSSIONS_SUPPORT_EMAIL: "odl-discussions-ci-support@mit.edu"
    OPENSEARCH_INDEX: "discussions-ci"
    OPENSEARCH_SHARD_COUNT: "2"
    OPENSEARCH_URL: 'https://search-opensearch-open-ci-gkxs5qardmug7pc472eznyfety.us-east-1.es.amazonaws.com'
    PGBOUNCER_DEFAULT_POOL_SIZE: "50"
    PGBOUNCER_MAX_CLIENT_CONN: "500"
    PGBOUNCER_MIN_POOL_SIZE: "20"
    SOCIAL_AUTH_MICROMASTERS_LOGIN_URL: "https://micromasters-ci.odl.mit.edu/login/edxorg/?next=/discussions/"
    SOCIAL_AUTH_OL_OIDC_OIDC_ENDPOINT: "https://sso-ci.ol.mit.edu/realms/olapps"
    SOCIAL_AUTH_SAML_SP_ENTITY_ID: "https://discussions-ci.odl.mit.edu/saml/metadata"
    TIKA_SERVER_ENDPOINT: "https://tika-ci.ol.mit.edu"
    USERINFO_URL: "https://sso-ci.ol.mit.edu/realms/olapps/protocol/openid-connect/userinfo"
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
