---
secretsprovider: awskms://alias/PulumiSecrets
encryptedkey: AQICAHionUR8LBW1ALuVC0rCH3AE2oQIfGMCx3XmpDH9HjM2LQG5amoQga3nCgWLiRLTe1ZsAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgnZ6Kfd8/ypWGhAQAgEQgDtvDma0V46aUE4viGtyBXDC4Hi+uWZIhOAEw4ylgN46pmwqVJCT1uBJ/aCymt8nX3fYSRXg4v7zHrS9Cw==
config:
  aws:region: us-east-1
  heroku:app_id:
    secure: v1:t1FrUGogN21TTq/Q:sSYVl0zN2yuAoRDSXFnXnzMg1Fzp9a6g7D/UXSJ44qXT48MlmwnqaAuMW5/z7uTAiXL/TQ==
  heroku_app:vars:
    ACCESS_TOKEN_URL: "https://sso-qa.ol.mit.edu/realms/olapps/protocol/openid-connect/token"
    AUTHORIZATION_URL: "https://sso-qa.ol.mit.edu/realms/olapps/protocol/openid-connect/auth"
    AWS_STORAGE_BUCKET_NAME: 'odl-discussions-rc'
    CELERY_WORKER_MAX_MEMORY_PER_CHILD: "125000"
    CLOUDFRONT_DIST: "d1d3xcwjqmwwj2"
    CORS_ALLOWED_ORIGINS: '["https://micromasters-rc.odl.mit.edu", "https://ocwnext-rc.odl.mit.edu",
      "https://ocw-next.netlify.app", "https://ol-devops-ci.odl.mit.edu", "https://draft-qa.ocw.mit.edu",
      "https://live-qa.ocw.mit.edu"]'
    DEBUG: "False"
    EDX_LEARNING_COURSE_BUCKET_NAME: "edxorg-qa-edxapp-courses"
    ENABLE_INFINITE_CORRIDOR: "True"
    FEATURE_COURSE_UI: "True"
    FEATURE_KEYCLOAK_ENABLED: "True"
    GA_G_TRACKING_ID: "G-N6Y7B0Z3JL"
    GA_TRACKING_ID: "UA-5145472-29"
    INDEXING_API_USERNAME: "od_mm_rc_api"
    KEYCLOAK_BASE_URL: "https://sso-qa.ol.mit.edu"
    KEYCLOAK_REALM_NAME: "olapps"
    MAILGUN_FROM_EMAIL: 'MIT Open <no-reply@discussions-mail.odl.mit.edu'
    MICROMASTERS_CATALOG_API_URL: "https://micromasters-rc.odl.mit.edu/api/v0/catalog/"
    MICROMASTERS_COURSE_URL: "https://micromasters-rc.odl.mit.edu/api/v0/courseruns/"
    MAILGUN_SENDER_DOMAIN: "discussions-mail.odl.mit.edu"
    MAILGUN_URL: "https://api.mailgun.net/v3/discussions-mail.odl.mit.edu"
    MICROMASTERS_BASE_URL: "https://micromasters-rc.odl.mit.edu"
    MICROMASTERS_EXTERNAL_LOGIN_URL: "https://micromasters-rc.odl.mit.edu/discussions"
    NEW_RELIC_APP_NAME: "discussions-rc"
    OCW_ITERATOR_CHUNK_SIZE: "300"
    OCW_LEARNING_COURSE_BUCKET_NAME: "open-learning-course-data-rc"
    OCW_NEXT_AWS_STORAGE_BUCKET_NAME: "ol-ocw-studio-app-qa"
    OCW_NEXT_BASE_URL: "https://live-qa.ocw.mit.edu/"
    OCW_NEXT_LIVE_BUCKET: "ocw-content-live-qa"
    OCW_UPLOAD_IMAGE_ONLY: "True"
    OIDC_ENDPOINT: "https://sso-qa.ol.mit.edu/realms/olapps"
    OPEN_DISCUSSIONS_BASE_URL: "https://discussions-rc.odl.mit.edu"
    OPEN_DISCUSSIONS_COOKIE_NAME: "discussionsrc"
    OPEN_DISCUSSIONS_COOKIE_DOMAIN: "odl.mit.edu"
    OPEN_DISCUSSIONS_CORS_ORIGIN_WHITELIST: '["https://micromasters-rc.odl.mit.edu",
      "https://ocwnext-rc.odl.mit.edu", "https://ocw-next.netlify.app", "https://ol-devops-ci.odl.mit.edu",
      "https://draft-qa.ocw.mit.edu", "https://live-qa.ocw.mit.edu"]'
    OPEN_DISCUSSIONS_ENVIRONMENT: "rc"
    OPEN_DISCUSSIONS_LOG_LEVEL: "INFO"
    OPEN_DISCUSSIONS_SUPPORT_EMAIL: "odl-discussions-rc-support@mit.edu"
    OPENSEARCH_INDEX: "discussions-rc"
    OPENSEARCH_SHARD_COUNT: "2"
    OPENSEARCH_URL: 'https://search-opensearch-open-qa-76e2mth7e5hvtclhuhh7uckoiu.us-east-1.es.amazonaws.com'
    PGBOUNCER_DEFAULT_POOL_SIZE: "50"
    PGBOUNCER_MAX_CLIENT_CONN: "500"
    PGBOUNCER_MIN_POOL_SIZE: "20"
    SOCIAL_AUTH_MICROMASTERS_LOGIN_URL: "https://micromasters-rc.odl.mit.edu/login/edxorg/?next=/discussions/"
    SOCIAL_AUTH_OL_OIDC_OIDC_ENDPOINT: "https://sso-qa.ol.mit.edu/realms/olapps"
    SOCIAL_AUTH_SAML_SP_ENTITY_ID: "https://discussions-rc.odl.mit.edu/saml/metadata"
    TIKA_SERVER_ENDPOINT: "https://tika-qa.ol.mit.edu"
    USERINFO_URL: "https://sso-qa.ol.mit.edu/realms/olapps/protocol/openid-connect/userinfo"
  vault:address: https://vault-qa.odl.mit.edu
  vault_server:env_namespace: operations.qa
