---
secretsprovider: awskms://alias/PulumiSecrets
encryptedkey: AQICAHionUR8LBW1ALuVC0rCH3AE2oQIfGMCx3XmpDH9HjM2LQEmOuKx7TjiG3WvrduMXtibAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMsgzrV+TMGt9WcJXzAgEQgDtNRhDDddtK6dqcatu+JoRNY+vrvaHPwOxI/uUO7MWEM1WVMEmRYyE1V0LVXKNZs8bLOHrSI3QxYilLxA==
config:
  aws:region: us-east-1
  heroku:app_id:
    secure: v1:WNbvtJ6EDIiQuDbl:8crTsAfkRMBwW5Jbxf/FbJEb1c0Zdn8ry8QaqGoLKDTu6Ttmqoh0tFhG5ve3xEIm9xrUjA==
  heroku_app:vars:
    CONCOURSE_URL: https://cicd-qa.odl.mit.edu
    CONTENT_FILE_SEARCH_API_URL: 'https://mitopen.odl.mit.edu/api/v1/content_file_search/'
    COURSE_SEARCH_API_URL: 'https://mitopen.odl.mit.edu/api/v1/learning_resources_search/'
    DRIVE_UPLOADS_PARENT_FOLDER_ID: 1H4HCvbmY7v5YZFeqSlbCI1TFC5MXTMY4
    FEATURE_USE_LOCAL_STARTERS: "True"
    GIT_ORGANIZATION: "ocw-content-ci"
    GITHUB_APP_ID: 12
    GITHUB_RATE_LIMIT_CHECK: "False"
    GITHUB_WEBHOOK_BRANCH: 'release-candidate'
    GTM_ACCOUNT_ID: GTM-5JZ7X78
    MAILGUN_FROM_EMAIL: 'MIT OCW <no-reply@ocw-ci.mail.odl.mit.edu'
    MAILGUN_SENDER_DOMAIN: 'ocw-ci.mail.odl.mit.edu'
    MAILGUN_URL: https://api.mailgun.net/v3/ocw-ci.mail.odl.mit.edu
    OCW_HUGO_THEMES_SENTRY_DSN: 'https://eee58f41dda54d2b814296e12dced4b7@o48788.ingest.sentry.io/5304953'
    OCW_IMPORT_STARTER_SLUG: course
    OCW_MASS_BUILD_BATCH_SIZE: '160'
    OCW_MASS_BUILD_MAX_IN_FLIGHT: '20'
    OCW_STUDIO_BASE_URL: https://ocw-studio-ci.odl.mit.edu/
    OCW_STUDIO_LOG_LEVEL: INFO
    OCW_STUDIO_SUPPORT_EMAIL: 'ocw-studio-ci-support@mit.edu'
    SENTRY_LOG_LEVEL: 'WARN'
    SOCIAL_AUTH_SAML_SP_ENTITY_ID: 'https://ocw-studio-ci.odl.mit.edu/saml/metadata'
    STATIC_API_BASE_URL_TEST: 'https://test-qa.ocw.mit.edu/'
    YT_PROJECT_ID: 'ovs-youtube-qa'
    POST_TRANSCODE_ACTIONS: 'videos.api.update_video_job'
    VIDEO_S3_UPLOAD_PREFIX: 'gdrive_uploads'
    TRANSCODE_JOB_TEMPLATE: './videos/config/mediaconvert.json'
  ocw_studio:app_domain: ocw-studio-ci.odl.mit.edu
  ocw_studio:k8s_deploy: "true"
  ocw_studio:db_password:
    secure: v1:PMhnJY0c/38fxcK/:HwHpoUXfP5YTzXq/3cyZUj4eRjCmNkdScLTGca863qCG/U1Py2BHwJXHiM8KPXx9NJufyVDzNtf79Ss7UTEcKOmM+M+8NXFE6I8UCapuui3yi52KFOWk7o6X
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
  redis:password:
    secure: v1:RoiGKrOlnqIsp8nb:388ZZ/xuvxVJ4DiHlUQRkdAlRiCqWucphQ7KWxWFxnZtOGle/KpHzC/ZmRtU04ENQFVsqDBopkr8
