---
secretsprovider: awskms://alias/infrastructure-secrets-qa
encryptedkey: AQICAHi7xhTkB8tf1ObyPMxDhODJja4Mn4jyIo32zZVlOiZPFgEl41q95kWsVHZvJHSCqWIxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpQTBAjNd/3wDdPIeAgEQgDtsiZwjL/rgq3Ayh3VO/ZDzy9iiLjnoE3KtTjKil/pDXMzmHUHWfscSxBdmykPUI6KIFPfaaj4qHdh2Kg==
config:
  aws:region: us-east-1
  consul:address: https://consul-xpro-qa.odl.mit.edu
  edxnotes:acm_cert_domain: '*.xpro.mit.edu'
  edxnotes:auto_scale:
    desired: 1
    max: 2
    min: 1
  edxnotes:business_unit: mitxpro
  edxnotes:dns_zone: xpro
  edxnotes:domain: xpro-notes-qa.xpro.mit.edu
  edxnotes:target_vpc: applications_vpc
  vault:address: https://vault-qa.odl.mit.edu
  vault_server:env_namespace: operations.qa
