---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHg/+QzF9hGIaoayDitgnEVHEhuaANONVQQOnqpkIsol1gF4g94MDlsx3nJ1Hyfib34cAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkoRcrjxSQdAr4CPxAgEQgDstn4GttXg+xdkgiSqVyjPNY+DZDF+t4oCIP8E5u52G5sZdg6I8QuVdzhEVYuuJB/nNXOzzl8zSAwChKg==
config:
  aws:region: us-east-1
  consul:address: https://consul-xpro-production.odl.mit.edu
  edxnotes:acm_cert_domain: '*.xpro.mit.edu'
  edxnotes:auto_scale:
    desired: 2
    max: 3
    min: 1
  edxnotes:business_unit: mitxpro
  edxnotes:dns_zone: xpro
  edxnotes:domain: xpro-notes.xpro.mit.edu
  edxnotes:target_vpc: applications_vpc
  edxnotes:deploy_to_k8s: true
  vault:address: https://vault-production.odl.mit.edu
  vault_server:env_namespace: operations.production
