---
secretsprovider: awskms://alias/infrastructure-secrets-qa
encryptedkey: AQICAHi7xhTkB8tf1ObyPMxDhODJja4Mn4jyIo32zZVlOiZPFgHMxGt/KjhBHNA7kHSoJAckAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSOb4NMN1cZSYlG6cAgEQgDtZvGETtN2EEF6EvOPpxyUGqnOtXBYE5TT5vzYoK/UaZunRRCBBO3s1DFpStF/sQIn62brM9wuVHPcsEQ==
config:
  aws:region: us-east-1
  consul:address: https://consul-mitxonline-production.odl.mit.edu
  edxnotes:acm_cert_domain: 'notes.learn.mit.edu'
  edxnotes:auto_scale:
    desired: 2
    max: 3
    min: 1
  edxnotes:business_unit: mitxonline
  edxnotes:dns_zone: learn
  edxnotes:domain: notes.learn.mit.edu
  edxnotes:target_vpc: applications_vpc
  vault:address: https://vault-production.odl.mit.edu
  vault_server:env_namespace: operations.production
