---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHi+npazf3LfzV9oCtcYyCMYLOzaQhbo9xt6lJVVpz9tkQExfDcBYiabYdbVUmHx6nrwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUnGBBiSqxOWoZhwQAgEQgDsXt4IWVM5rNZmUecOSeYCspFlEnVGNtuj1QRKXBJCR/ko/YzUzCvrzea4p9i4y+fK5O9YTl0gFg2YzeA==
config:
  aws:region: us-east-1
  consul:address: https://consul-mitx-staging-ci.odl.mit.edu
  edxnotes:acm_cert_domain: '*.mitx.mit.edu'
  edxnotes:auto_scale:
    desired: 1
    max: 2
    min: 1
  edxnotes:business_unit: residential-staging
  edxnotes:dns_zone: mitx
  edxnotes:domain: staging-notes-ci.mitx.mit.edu
  edxnotes:target_vpc: residential_mitx_staging_vpc
  edxnotes:deploy_to_k8s: true
  edxnotes:cluster: residential
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
