---
secretsprovider: awskms://alias/infrastructure-secrets-qa
encryptedkey: AQICAHi7xhTkB8tf1ObyPMxDhODJja4Mn4jyIo32zZVlOiZPFgHglno9Eeaghj0put6CZrFAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMyiTEBLc97B/fGZVBAgEQgDvaMqDrLZ3+EBMQNkxYhjALZ+bmrlPGr69yr+QYDeJiIaCeKRQkCjYvkJ1tfOjG6ZEjRf6fyFPhGV4QMg==
config:
  aws:region: us-east-1
  consul:address: https://consul-mitx-qa.odl.mit.edu
  edxnotes:acm_cert_domain: '*.mitx.mit.edu'
  edxnotes:auto_scale:
    desired: 1
    max: 2
    min: 1
  edxnotes:business_unit: residential
  edxnotes:dns_zone: mitx
  edxnotes:domain: notes-qa.mitx.mit.edu
  edxnotes:target_vpc: residential_mitx_vpc
  edxnotes:cluster: residential
  vault:address: https://vault-qa.odl.mit.edu
  vault_server:env_namespace: operations.qa
