---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHi3MZ/Pjy2dahB1Qm+zKkKDPV1b9MYPGp7k649HPjmOHAEhDcI6l53dL0ppsATEQTcTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpQynaF6Qix/ekkzIAgEQgDvwHROWXxgzH8lf80JWKyHIkWmNhh5V0uIEtIRCL0U7Z62a9vMpKlCimWYKZWIM6VdsloXvrIxBGKcaYQ==
config:
  aws:region: us-east-1
  consul:address: https://consul-mitxonline-ci.odl.mit.edu
  edxnotes:acm_cert_domain: 'notes.ci.learn.mit.edu'
  edxnotes:auto_scale:
    desired: 1
    max: 2
    min: 1
  edxnotes:business_unit: mitxonline
  edxnotes:dns_zone: learn
  edxnotes:domain: notes.ci.learn.mit.edu
  edxnotes:target_vpc: applications_vpc
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
