---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHi+npazf3LfzV9oCtcYyCMYLOzaQhbo9xt6lJVVpz9tkQGLY0N6iOKXI4IbKVL7IjjZAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwH/7LpMAbpSkmD5YAgEQgDtmsSbe/eU9yIh7sxqmxfbq/aqXi1UbK+xCjAssWBUNzl6GZy2NfpgjEV5AKSCuQYl8JVm3GzjSfg0SEQ==
config:
  aws:region: us-east-1
  consul:address: https://consul-mitx-ci.odl.mit.edu
  edxnotes:acm_cert_domain: '*.mitx.mit.edu'
  edxnotes:auto_scale:
    desired: 1
    max: 2
    min: 1
  edxnotes:business_unit: residential
  edxnotes:dns_zone: mitx
  edxnotes:domain: notes-ci.mitx.mit.edu
  edxnotes:target_vpc: residential_mitx_vpc
  edxnotes:deploy_to_k8s: true
  edxnotes:cluster: residential
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
