---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHi+npazf3LfzV9oCtcYyCMYLOzaQhbo9xt6lJVVpz9tkQHmbQbdOIGG4Jt34XVtsKrHAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzjNghqk4vTeob3lJAgEQgDt7H0yPqnjaQpouv/pngrLocorB4cYIcu+1zjTT95OxLKYWG6n4zAOokfTG64Ut0fyLkxA2EvI7vytTgg==
config:
  aws:region: us-east-1
  consul:address: https://consul-micromasters-ci.odl.mit.edu
  consul:scheme: https
  heroku:user: "mitx-devops"
  heroku:app_id:
    secure: v1:sgsxJ/o4VFRg9Gwo:3K5dWKF4yiNcZ3oQ1/INdBMOionm5uqiK03t5m+wUmg8FrqG6mIccjDghAel1hKHBBfMKw==
  heroku_app:vars:
    ALLOWED_HOSTS: '["micromasters-ci.odl.mit.edu"]'
    AWS_STORAGE_BUCKET_NAME: "ol-micromasters-app-ci"
    CLOUDFRONT_DIST: ""
    CYBERSOURCE_REFERENCE_PREFIX: "ci"
    CYBERSOURCE_SECURE_ACCEPTANCE_URL: "https://testsecureacceptance.cybersource.com/pay"
    EDXORG_BASE_URL: "https://lms-ci.mitx.mit.edu"
    EDXORG_CALLBACK_URL: "https://lms-ci.mitx.mit.edu"
    FEATURE_EXAMS_CARD_ENABLED: "False"
    GA_TRACKING_ID: "UA-5145472-14"
    GTM_CONTAINER_ID: "GTM-NB27R8L"
    MAILGUN_FROM_EMAIL: "no-reply@micromasters-rc-mail.odl.mit.edu"
    MAILGUN_URL: "https://api.mailgun.net/v3/micromasters-rc-mail.odl.mit.edu"
    MICROMASTERS_BASE_URL: "https://micromasters-ci.odl.mit.edu"
    MICROMASTERS_CORS_ORIGIN_WHITELIST: "[]"
    MICROMASTERS_ENVIRONMENT: "ci"
    MICROMASTERS_LOG_LEVEL: "DEBUG"
    MIDDLEWARE_FEATURE_FLAG_QS_PREFIX: ""
    MITXONLINE_BASE_URL: ""
    MITXONLINE_CALLBACK_URL: ""
    MITXONLINE_URL: ""
    PGBOUNCER_DEFAULT_POOL_SIZE: 50
    PGBOUNCER_MAX_CLIENT_CONN: 1000
  micromasters:db_password:
    secure: v1:DTEttuHYUMFQ5AJM:FSsYgItu3JT8hNcO/kz/JJn3t/dSHEWl5RSNUzlErvov6GDajBte9cvhMjrWi1itHopHJCkiseHdBxjz8Iulaodo9eeHQwSMrAq3+HuWgXE=
  micromasters:domain: micromasters-ci.odl.mit.edu
  vault:address: https://vault-ci.odl.mit.edu
  vault_server:env_namespace: operations.ci
