---
secretsprovider: awskms://alias/PulumiSecrets
encryptedkey: AQICAHionUR8LBW1ALuVC0rCH3AE2oQIfGMCx3XmpDH9HjM2LQFDk9oNre+ZYrl+lNkZ9CehAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNe2uymJF5010Anx2AgEQgDsOVtKxfazfL9cTImahAr3lIo2Q1gwQWyMVJEq5oCuzrd+CLl5Ai1EhxfMPvs+z7+BhfIhWlqF0e/Kv3g==
config:
  aws:region: us-east-1
  aws:skip_metadata_api_check: false
  aws:skip_credentials_validation: false
  sign_and_verify:domain: digitalcredentials.odl.mit.edu
  sign_and_verify:docker_label: release
  sign_and_verify:hmac_secret:
    secure: v1:nVPwlAPwhiCebLXj:UUB5tQvAaaXhkWqwUyw7wcM3I7muH17DCnhVvitguUSqph65mFcKiolNkfs2eV1YPeKu5p6hTYfP4hlmyJUrL2F9k3Y+cl0DWpeX4iSShh2l6DppFKIHt9bBoA==
  sign_and_verify:oidc_issuer_url: https://xpro.mit.edu
