---
secretsprovider: awskms://alias/PulumiSecrets
encryptedkey: AQICAHionUR8LBW1ALuVC0rCH3AE2oQIfGMCx3XmpDH9HjM2LQHEa3zOh6zzfOFMSvj2V8EEAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVRuXAGgmailDruXkAgEQgDsWPumXraA6JEpaomYG1FFFCq2aCcGR7H2Z4LSu67H/0K1h2wZ9VCmrYB2NLqUqgY/e8vdDFNoV7CmKhQ==
config:
  aws:region: us-east-1
  aws:skip_metadata_api_check: false
  aws:skip_credentials_validation: false
  sign_and_verify:docker_label: latest
  sign_and_verify:domain: digitalcredentials-rc.odl.mit.edu
  sign_and_verify:hmac_secret:
    secure: v1:1au0eh6XI6+9GEGf:PzkSbnvvewPbZa6cOH8jNPb4+xbM64rLhZXjtH4D3imKIODlC6tNJp95eeKWYG3UELL+hNIxj/39IptZCpFKFkePZEvQHDYN+6lW0uQghHNXo91yqHQWfTCl
  sign_and_verify:oidc_issuer_url: https://rc.xpro.mit.edu
