---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHhMkpkBpCvmFjhyfy75ENALRrbg42uOs9cUsFNLXqPnagFTJi+CTcIkt99X+nBUyHZtAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMMlrxVpWJh0ZeaLf9AgEQgDueau/6fxismCHgjDagynXJCxDv4CIGU4pG+BU6DdshEiYAVUJUWBaAUVWCeRA1vuYHZfSmoDEAa9LX2Q==
config:
  vault:address: https://vault-ci.odl.mit.edu
  slack:channel_name: kubewatch-applications-ci
