---
secretsprovider: awskms://alias/infrastructure-secrets-production
config:
  vault:address: https://vault-production.odl.mit.edu
  slack:channel_name: kubewatch-applications-production
encryptedkey: AQICAHi3FG4qowC3UzOLWOAA4Y9/RTwqKjovG3wyVVYDxkR+zAFCdRPVlsWoP5ZLXtsZ9ia9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMNpndOSZtgrW8rRe+AgEQgDvwR49U/70xmPR4Bf7Dt4TjXMGtxDDHrNp7VOFSlN7oeL8/nPaygpS14dC+tgnZZiPcL5+WUzFSr9g0mg==
