---
secretsprovider: awskms://alias/infrastructure-secrets-production
encryptedkey: AQICAHi3FG4qowC3UzOLWOAA4Y9/RTwqKjovG3wyVVYDxkR+zAEQSzOXcwWqoKOsuNhQanLhAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtfhGqjMHIVcbAtDUAgEQgDvlaGoyAyk/AY2fzDUtGaiA5yzJjwbdCq90LkCH5nuk5n0vIeBFZD2H1tid4uJTG9lwE5EpJ7G2LJp1Cw==
config:
  nextjs:appzi_url:
    secure: v1:NN7tWDa0Wxa5T54D:Yd+275vxZ40KZWjRxzuOfdrwZxDSt2g6IvruSU+xZwMxRYtOFOap1DPfnbWpMDrKzQYQ
  nextjs:csrf_cookie_name: "learn_csrftoken"
  nextjs:domain: "next.learn.mit.edu"
  nextjs:embedly_key:
    secure: v1:k5VhDKIu3fRgFRZK:uD6fSyGLF3QhKYIbgUJ3/p+3x+fmtQqU4UpuLvJa72UbhDHf1s9t2O2NMQ7492bw
  nextjs:mitlearn_api_base_url: "https://api.learn.mit.edu"
  nextjs:mitol_noindex: "false"
  nextjs:mitxonline_base_url: "https://api.learn.mit.edu/mitxonline"
  nextjs:origin: "https://learn.mit.edu"
  nextjs:pod_count: 5
  nextjs:posthog_api_host: "https://ph.ol.mit.edu"
  nextjs:posthog_api_key:
    secure: v1:oa2Jq3cyaLttgxTD:U4odgKoAnfUbsDPprhv4ZH3nnJlrgkeM9RS57daOOcx9hFHxUd96mX66kQ8sfdFWKUPMz9FKh+dzsNo1NzmA
  nextjs:posthog_project_id:
    secure: v1:IY8kATrcMVk0PJdB:U5qEC1Iuoxnm707xldqg5SXBSPb2
  nextjs:recommendation_endpoint: "https://api.learn.mit.edu/ai/http/recommendation_agent/"
  nextjs:sentry_dsn:
    secure: v1:ox5oolYtQIKsmojo:0ogC8iKnU4ECkqSmDxGTb3dHlGU1oQFMOjhIkVLYrYNcc53LGHd3IdaCyLgAXtyyEkE+/Qk+d6l6WpFnKpPzmprsNeWsV5YhQYaGnQhKYBwaaDav4+HPY7S/xXRqwQE3DjbZBA==
  nextjs:sentry_env: "production"
  nextjs:syllabus_endpoint: "https://api.learn.mit.edu/ai/http/syllabus_agent/"
  nextjs:optimize_images: "false"
