---
secretsprovider: awskms://alias/infrastructure-secrets-ci
encryptedkey: AQICAHhMkpkBpCvmFjhyfy75ENALRrbg42uOs9cUsFNLXqPnagHZP+g+0MtIz9uwsgVicDnKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2YQOv1g59zat+SGGAgEQgDte/naCMiYBXxI8PbZpq7Ym2AxPxpI/xrJ6UcedPce/aWMSBSKBcWtJi606VywgBQ1bo5YXgYdcb9j0/g==
config:
  qdrant:domain: ci.qdrant.ol.mit.edu
  qdrant:api_key:
    secure: v1:5RXi+XnjhsM5nCXB:vjULDbY9qGLrOWuHIv/TFRkgPRtbeBrphY02Dkb7ZEWBUYz5eFmSUCddbDB6CqeksKMAMSex+e8zi4Zd8ls0zL6JCcc1l6wAv6AZ1tSKNuM=
  qdrant:replica_count: 3
  qdrant:persistence_size: 200Gi
  qdrant:snapshot_size: 200Gi
  qdrant:snapshot_enabled: true
  qdrant:cluster_enabled: true
  qdrant:service_type: NodePort
  qdrant:enable_topology_spread: true
  qdrant:pod_disruption_budget_enabled: true
  qdrant:pod_disruption_budget_max_unavailable: 1
  qdrant:cpu_request: 2000m
  qdrant:cpu_limit: 3000m
  qdrant:memory_request: 4Gi
  qdrant:memory_limit: 12Gi
