---
slack-token: ENC[AES256_GCM,data:XOSv9F7iIAQXQFB4o2rrO1VH2hhhY037fuLN2x30MbKkX1sb61xYnz9Dvz/BUaFmUgEF7ZaX,iv:rbj4echO3bgsGqhe9ukgQFj3WnroqEYCo3pVtn1AFxI=,tag:RHveIDhUAISFHME2Uu8ucg==,type:str]
sops:
  kms:
  - arn: arn:aws:kms:us-east-1:610119931565:alias/infrastructure-secrets-ci
    created_at: "2025-06-05T19:01:31Z"
    enc: AQICAHi3MZ/Pjy2dahB1Qm+zKkKDPV1b9MYPGp7k649HPjmOHAF08aPgLgFNC1+iWhcwGGahAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7+JaE1oq9SqJUY7FAgEQgDs3AOAqkoPz+13c8YAOHBAqWwylieFU/ks5lIxSLqBDbwdrdn7dmxPECQafoTc4SlcJlP3GWXGcYnw1kw==
    aws_profile: ""
  hc_vault:
  - vault_address: https://vault-ci.odl.mit.edu
    engine_path: infrastructure
    key_name: sops
    created_at: "2025-06-05T19:01:31Z"
    enc: vault:v1:NU59g4laLzd+wXtMaKoCyOsLqgOR0oVtJAMo2/KidA4hYbo9DyKFPJZcg7yhDoAwSc4zx5QsNNv5piTe
  lastmodified: "2025-11-04T20:22:55Z"
  mac: ENC[AES256_GCM,data:Ec/omUtQhlInh9IsN86YCC3YjqLUki72EhX7rnzUFgWUy9GEAoDGbMgg4gp66cdXrbXWQAwfANZDwFxebyVvIHOHfZPg+oaAvimijJmSoxrzvsykbOvmZPrhnlkIyGmVaaghKWL5FKbrk2JS86yuz6snvbPerj3ekAk1O0whdaY=,iv:BiAZbF4m4nJhh+yhB498WtrinFbBfz8I3umrNyFiZ2w=,tag:3YQyqv+hpySilffaRpZXeA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
