---
slack-token: ENC[AES256_GCM,data:Zf0vwb/pmPjIxXdbz2a2YKaqB6Lu7ZBzbr9FiPhaYli9n9ZHXejvfLCHZAZGZiO10Z+7+nSogwyYMpsQK5YJf8Uup0gANWXcC2Sx+o5O9gcee9l9YN3oiIdHZHfJIu7gcw==,iv:U8iHOOeHzy1EZQ/mpoEDamsdH1Lmx2jSm3yAUWspz7A=,tag:mSIqn7Fjb2S9YkhWf38ShA==,type:str]
slack-webhook-url: ENC[AES256_GCM,data:yJ8J5hhnXWg0W/AMIbvPLExfx3GVx2kNO6DIzi+KJXcpk/LSIa2RNEUxrsQbrrEwcoeULK8oT7UbxTPLu88rujQZ08JMx7MhumFh/d9z1g==,iv:0SYWwX2wmfPCne6njYseR2sB9mlA3LQVb0D4xY5fsTg=,tag:AZHeFYa43MlgTa4T0yVCiQ==,type:str]
sops:
  kms:
  - arn: arn:aws:kms:us-east-1:610119931565:alias/infrastructure-secrets-ci
    created_at: "2025-06-05T19:01:31Z"
    enc: AQICAHi3MZ/Pjy2dahB1Qm+zKkKDPV1b9MYPGp7k649HPjmOHAF08aPgLgFNC1+iWhcwGGahAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7+JaE1oq9SqJUY7FAgEQgDs3AOAqkoPz+13c8YAOHBAqWwylieFU/ks5lIxSLqBDbwdrdn7dmxPECQafoTc4SlcJlP3GWXGcYnw1kw==
    aws_profile: ""
  hc_vault:
  - vault_address: https://vault-ci.odl.mit.edu
    engine_path: infrastructure
    key_name: sops
    created_at: "2025-06-05T19:01:31Z"
    enc: vault:v1:NU59g4laLzd+wXtMaKoCyOsLqgOR0oVtJAMo2/KidA4hYbo9DyKFPJZcg7yhDoAwSc4zx5QsNNv5piTe
  lastmodified: "2025-11-03T20:34:31Z"
  mac: ENC[AES256_GCM,data:rDXgqp+lDukIN/EXxzZBHShDwsVx9VR5+5h4EL3+WbNSsRE4RqZbCGWBoXqU13UZJBz0YQu40M58o1PVsB8yrIOALd+Z4XXOhpV+uVZOYF9Jss9vAQeSyL6VQX7ehUG64Vi7YCyLFxl2OUgiShgHGMpBbCOswWotmuX/Kf+5qtM=,iv:tiGB4lUkB7X/2ah3iWLLP9WmyGEggTxSsNg/RG/Yxqw=,tag:pMtZaoCFghNxr3D7DgdQzQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
