---
slack-token: ENC[AES256_GCM,data:ezrrxyTk/r7LetUKgu2auMC++gGkZHKeuZrKpK+xKSSzcjuCILuSGdG0fOs0oex3gk7ZKcp3,iv:WOM6SzTpimuXFzFG8ApjLgiLutbRCqT4zR8iBmOoKQ0=,tag:SrLbj4DExlfFR/m0AOZQ6g==,type:str]
sops:
  kms:
  - arn: arn:aws:kms:us-east-1:610119931565:alias/infrastructure-secrets-production
    created_at: "2025-11-05T21:38:28Z"
    enc: AQICAHi3FG4qowC3UzOLWOAA4Y9/RTwqKjovG3wyVVYDxkR+zAGQOS7cLEabvOQkm5yuHJdwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMV0wqofiHhq18zAZjAgEQgDsistNLHsaJ5WuQf06bkB7qIsBuO6tBXPH7d3VIVHg3DRN32+VQ35XhJujEZRdcwQKdLwP4WgkPhYJw3g==
    aws_profile: ""
  lastmodified: "2025-11-05T21:45:11Z"
  mac: ENC[AES256_GCM,data:+c9KkdsDK1WJUWMtdwjAJ1jsHE+vPyAOWNaFqLGKatcibdWWKTd+uYUNjluwLcPNXeNkmy3DnmUxP3Dwn6EFd42b2104PLczVcOkvQX3TwEWh/bfxbJTspMD92iMdYJceWK2Os1OjQ/TQ+jhgcy50/7/Y6//ZxtDZZ095wEKnEw=,iv:hy+0dV0Kvk4iM+tr6YdFbaNrRRtFet0f/EL/zKOMuAI=,tag:eXe36pDlofIZf32eO02STg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
