---
slack-token: ENC[AES256_GCM,data:KAFgbs5BjuiuDiWXKGZnhlGeXgSNNlwrWcQdACqPKyX5SaeyO6ZjDJvP7hjjTILbc+/lwEGC,iv:7RGFgjwM7xrOukm3/LsjzmF/Y6TINK9hZSj/Am4JfSg=,tag:xDLwYidmnpJdQFyz3UntWQ==,type:str]
sops:
  kms:
  - arn: arn:aws:kms:us-east-1:610119931565:alias/infrastructure-secrets-qa
    created_at: "2025-11-05T21:38:36Z"
    enc: AQICAHjZAY5LtmRWGljev0oiDGn0jR5cRwD4IVXCn50TW5i0qQFEYevVd7DuMnW9rJdnlVktAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfJdS+q6ZCnZ6MlcjAgEQgDvpWua1WGGCxJxaJYMsUJxmXuvv2CrfMy2E6ZR9zPLoHZs2hlBY57Oj03Y4ODpeoEid48SXoc5AoojWrQ==
    aws_profile: ""
  lastmodified: "2025-11-05T21:43:26Z"
  mac: ENC[AES256_GCM,data:Qw+d3RuDYeBiFgGPP7WQ/CjesKPbUbnIUO/Tn09bUzBl6Je5gB2RrPmGg+KnerZczsIyocPj66yfRKN5oe7lp5FqcgeeJKj8Q8cSjmQLyL/uGOmQbg2SBkyQXHalBgw4R2yJ4zP5Z8yIHMSovp46nXR5BkU/8ORrPAAbGeteLxQ=,iv:cHi0JwddHlbIk+oYWiW1ohHTURmi4J0F0pOdVNiVneU=,tag:bAIsPt/ybbb3wzWBWHQUJQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
