---
secretsprovider: awskms://alias/PulumiSecrets
encryptedkey: AQICAHionUR8LBW1ALuVC0rCH3AE2oQIfGMCx3XmpDH9HjM2LQEGccCx6w+aU1z9VNPzXzwIAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkTCVUUXv23ZgiFtbAgEQgDusl6M2Rs0caUtV7jakSKAqsXTqm8f7M0UuEu0hjZ5KdbCp8HUDBShST/yKEpt0ExGXlODrlmL3gGN6fg==
config:
  aws:region: us-east-1
  consul:address: https://consul-data-production.odl.mit.edu
  dagster:db_password:
    secure: v1:CmsJwtIantGcm5j1:DL2TQs80PEYe2iZIvWKFA/oSy3Lh3uSdzVcYPDR28EmvCYsNGzUxrLpb2k0oZ5NTOu2pniwF
  dagster:domain: pipelines.odl.mit.edu
  dagster:edx_pipeline_gcs_courses_bucket_name: edxorg-production-edxapp-courses
  dagster:edx_pipeline_micromasters_bucket_name: ol-data-lake-mit-open-production
  dagster:edx_pipeline_micromasters_postgres_db_hostname: micromasters-db-read-replica.cbnm7ajau6mi.us-east-1.rds.amazonaws.com
  dagster:edx_pipeline_micromasters_postgres_db_name: micromasters
  dagster:edx_pipeline_mit_open_bucket_name: ol-data-lake-mit-open-production
  dagster:edx_pipeline_mit_open_postgres_db_hostname: production-apps-rds-postgresql-opendiscussions.cbnm7ajau6mi.us-east-1.rds.amazonaws.com
  dagster:edx_pipeline_mitx_enrollments_bucket_name: dagster-data-production
  dagster:edx_pipeline_mitx_online_edx_course_bucket: mitx-production-edxapp-courses
  dagster:edx_pipeline_mitx_online_purpose: residential-live-mitx
  dagster:edx_pipeline_mitxonline_edx_course_bucket_name: mitxonline-production-edxapp-courses
  dagster:edx_pipeline_mitxonline_purpose: mitxonline
  dagster:edx_pipeline_residential_mysql_db_hostname: edxapp-db-mitx-production.cbnm7ajau6mi.us-east-1.rds.amazonaws.com
  dagster:edx_pipeline_xpro_edx_bucket_name: dagster-data-production
  dagster:edx_pipeline_xpro_edx_course_bucket_name: xpro-production-edxapp-courses
  dagster:edx_pipeline_xpro_edx_xpro_purpose: mitx-etl-xpro-production
  vault:address: https://vault-production.odl.mit.edu
  vault_server:env_namespace: operations.production
